apiVersion: apps/v1
kind: Deployment
metadata:
  name: pal-tracker
  labels:
    app: pal-tracker
spec:
  selector:
    matchLabels:
      app: pal-tracker
      name: pal-tracker-pod
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: pal-tracker
        name: pal-tracker-pod
    spec:
      containers:
        - name: pal-tracker-container
          image: REGISTRY_HOST/pal-tracker:v0