# See https://docs.edukates.io/en/latest/runtime-environment/workshop-definition.html
apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnd-config-practices
spec:
  title: Deploy a Cloud Native App on a Modern Orchestrated Platform
  description: Deploy a Cloud Native App on a Modern Orchestrated Platform
  vendor: eduk8s.io
  difficulty: beginner
  duration: 240m
  url: https://github.com/platform-acceleration-lab/cnd-config-practices-eduk8s
  content:
    # Use the default image, one of the pre-existing ones, or you can build your own
    # https://docs.edukates.io/en/develop/runtime-environment/workshop-definition.html#container-image-for-the-workshop
    image: quay.io/eduk8s/jdk11-environment:master
    files: http://files.$(workshop_namespace).svc.cluster.local/workshop.tar.gz
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    dashboards:
    - name: Lecture
      url: https://vimeo.com/showcase/8261088/embed
  environment:
    objects:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: nginx
              image: cnd-config-practices
    - apiVersion: v1
      kind: Service
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files