apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: cnd-config-practices
spec:
  title: Configure a Cloud Native App on Kubernetes
  description: Configure a Cloud Native App on Kubernetes
  vendor: eduk8s.io
  difficulty: beginner
  duration: 240m
  url: https://github.com/platform-acceleration-lab/cnd-config-practices-eduk8s
  content:
    image: jdk11-environment:*
    files: http://files.$(workshop_namespace).svc.cluster.local/workshop.tar.gz
  session:
    namespaces:
      budget: large
    resources:
      memory: 2Gi
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
        vendor: octant
      editor:
        enabled: true
      registry:
        enabled: true
      docker:
        enabled: true
    dashboards:
    - name: Lecture
      url: https://vimeo.com/showcase/8381366/embed
  environment:
    objects:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: tarball-data
        namespace: $(workshop_namespace)
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        replicas: 1
        selector:
          matchLabels:
            deployment: files
        strategy:
          type: Recreate
        template:
          metadata:
            labels:
              deployment: files
          spec:
            containers:
            - name: nginx
              image: cnd-config-practices
              imagePullPolicy: IfNotPresent
    - apiVersion: v1
      kind: Service
      metadata:
        name: files
        namespace: $(workshop_namespace)
      spec:
        type: ClusterIP
        ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
        selector:
          deployment: files